### ISSUE TITLE
建议不用 ES6

### ISSUE THREAD

**Issue by hellodword** [CC11001100/crawler-js-hook-framework-public#1]
有些网站会不当使用 polyfill，或者不考虑命名，比如会写出如下代码，就会导致脚本报错

```js
function Map() {
    this.container = new Object();
}

Map.prototype.put = function(k, v) {
    this.container[k] = v;
}

Map.prototype.get = function(k) {
    return this.container[k];
}
```

https://github.com/CC11001100/crawler-js-hook-framework-public/blob/f59e9f5e34d35c87d4a38f1f0d63101331b104aa/001-cookie-hook/js-cookie-monitor-debugger-hook.js#L251-L256

为了方便随时在油猴里编辑，建议手写而不是编译

**Comment by CC11001100** [comment]
巨佬你好，我谨慎的思考了好多天这个问题应该如何解决 ：） 

我本来想回退来着，但是转念一想，对于“有些网站会不当使用 polyfill，或者不考虑命名”似乎应该是那个网站的问题，因为它们没有正确的实现规范啊，但是问题总归是需要解决的。

当然，回退ES6也是个很好的解决方案，能够避免很多问题，在我打算修改源码回退的时候，我突然想到，为什么不用babel呢！ 
主要是因为使用高版本的语法开发确实能够节省一些心力，使用插件去转换语法的话就不需要在写的时候一直去考虑“我这个用法是哪个版本的呢”之类的问题了。

所以，目前的解决方案是，对于比较特殊的网站，建议使用babel之类的将代码转换为低版本。

稍后会上传一个babel转换到es2015版本的（maybe....），当然，如果您能够给出目标网站的url以供测试就更好了！

**Comment by hellodword** [comment]
感谢大神回复

> 对于“有些网站会不当使用 polyfill，或者不考虑命名”似乎应该是那个网站的问题，因为它们没有正确的实现规范啊

是这样的没错，不过作为hack工具，可能不能强求目标按照规范来，毕竟…需要调试的目标代码不是我们写的

> 主要是因为使用高版本的语法开发确实能够节省一些心力

是的，我正是抱着反正不是我来改的心态提issue的
